# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Jorge Ruiz-Cabrejos, Health Data Scientist'
    twitter: 'jruizcabrejos'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Jorge R."

# Site footer
footer:
  copyright:
    notice: '© {year} Jorge Ruiz-Cabrejos. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false


plugins_css: ["custom","codefolding"]

############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding: false
# Set to show to show all by default, hide to hide all by default - don't put inside quotes
codefolding_show: show
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton: false
